// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: sdk/core/assets.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Assets
type Assets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Base asset.
	Base string `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Quote asset.
	Quote string `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *Assets) Reset() {
	*x = Assets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_core_assets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_core_assets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_sdk_core_assets_proto_rawDescGZIP(), []int{0}
}

func (x *Assets) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *Assets) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

var File_sdk_core_assets_proto protoreflect.FileDescriptor

var file_sdk_core_assets_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73, 0x64,
	0x6b, 0x22, 0x32, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x42, 0x53, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x61, 0x69,
	0x6b, 0x6f, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0xaa, 0x02, 0x0d, 0x4b, 0x61, 0x69,
	0x6b, 0x6f, 0x53, 0x64, 0x6b, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sdk_core_assets_proto_rawDescOnce sync.Once
	file_sdk_core_assets_proto_rawDescData = file_sdk_core_assets_proto_rawDesc
)

func file_sdk_core_assets_proto_rawDescGZIP() []byte {
	file_sdk_core_assets_proto_rawDescOnce.Do(func() {
		file_sdk_core_assets_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_core_assets_proto_rawDescData)
	})
	return file_sdk_core_assets_proto_rawDescData
}

var file_sdk_core_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_core_assets_proto_goTypes = []interface{}{
	(*Assets)(nil), // 0: kaikosdk.Assets
}
var file_sdk_core_assets_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_assets_proto_init() }
func file_sdk_core_assets_proto_init() {
	if File_sdk_core_assets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdk_core_assets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Assets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_core_assets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_assets_proto_goTypes,
		DependencyIndexes: file_sdk_core_assets_proto_depIdxs,
		MessageInfos:      file_sdk_core_assets_proto_msgTypes,
	}.Build()
	File_sdk_core_assets_proto = out.File
	file_sdk_core_assets_proto_rawDesc = nil
	file_sdk_core_assets_proto_goTypes = nil
	file_sdk_core_assets_proto_depIdxs = nil
}
