// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: sdk/core/envelope_status.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// EnvelopeStatus
// Status code of an API call
type EnvelopeStatus int32

const (
	// UNKNOWN result.
	EnvelopeStatus_UNKNOWN EnvelopeStatus = 0
	// Error result.
	EnvelopeStatus_ERROR EnvelopeStatus = 1
	// Successful result.
	EnvelopeStatus_SUCCESS EnvelopeStatus = 2
)

// Enum value maps for EnvelopeStatus.
var (
	EnvelopeStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "ERROR",
		2: "SUCCESS",
	}
	EnvelopeStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"ERROR":   1,
		"SUCCESS": 2,
	}
)

func (x EnvelopeStatus) Enum() *EnvelopeStatus {
	p := new(EnvelopeStatus)
	*p = x
	return p
}

func (x EnvelopeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_core_envelope_status_proto_enumTypes[0].Descriptor()
}

func (EnvelopeStatus) Type() protoreflect.EnumType {
	return &file_sdk_core_envelope_status_proto_enumTypes[0]
}

func (x EnvelopeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeStatus.Descriptor instead.
func (EnvelopeStatus) EnumDescriptor() ([]byte, []int) {
	return file_sdk_core_envelope_status_proto_rawDescGZIP(), []int{0}
}

var File_sdk_core_envelope_status_proto protoreflect.FileDescriptor

var file_sdk_core_envelope_status_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x73, 0x64, 0x6b, 0x2a, 0x35, 0x0a, 0x0e, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x02, 0x42, 0x58, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x64, 0x65, 0x65, 0x70, 0x2f, 0x6b, 0x61, 0x69, 0x6b, 0x6f, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64,
	0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b, 0x63, 0x6f, 0x72, 0x65, 0xaa, 0x02, 0x0d, 0x4b, 0x61,
	0x69, 0x6b, 0x6f, 0x53, 0x64, 0x6b, 0x2e, 0x43, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sdk_core_envelope_status_proto_rawDescOnce sync.Once
	file_sdk_core_envelope_status_proto_rawDescData = file_sdk_core_envelope_status_proto_rawDesc
)

func file_sdk_core_envelope_status_proto_rawDescGZIP() []byte {
	file_sdk_core_envelope_status_proto_rawDescOnce.Do(func() {
		file_sdk_core_envelope_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_core_envelope_status_proto_rawDescData)
	})
	return file_sdk_core_envelope_status_proto_rawDescData
}

var file_sdk_core_envelope_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_core_envelope_status_proto_goTypes = []interface{}{
	(EnvelopeStatus)(0), // 0: kaikosdk.EnvelopeStatus
}
var file_sdk_core_envelope_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_core_envelope_status_proto_init() }
func file_sdk_core_envelope_status_proto_init() {
	if File_sdk_core_envelope_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_core_envelope_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_core_envelope_status_proto_goTypes,
		DependencyIndexes: file_sdk_core_envelope_status_proto_depIdxs,
		EnumInfos:         file_sdk_core_envelope_status_proto_enumTypes,
	}.Build()
	File_sdk_core_envelope_status_proto = out.File
	file_sdk_core_envelope_status_proto_rawDesc = nil
	file_sdk_core_envelope_status_proto_goTypes = nil
	file_sdk_core_envelope_status_proto_depIdxs = nil
}
